"""Initial migration

Revision ID: 0c05d047390f
Revises: 
Create Date: 2025-11-06 17:24:40.923157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c05d047390f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the detection'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp when the detection occurred'),
    sa.Column('class_name', sa.String(), nullable=False, comment='Type of object detected'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Detection confidence score (0-1)'),
    sa.Column('image_path', sa.String(), nullable=False, comment='Path to the stored image file'),
    sa.Column('gps_lat', sa.Float(), nullable=True, comment='GPS latitude of the detection'),
    sa.Column('gps_lng', sa.Float(), nullable=True, comment='GPS longitude of the detection'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
