"""fix_detection_alert_relationships

Revision ID: 5a301775c55d
Revises: 9057408b1fdc
Create Date: 2025-11-08 10:19:05.928641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a301775c55d'
down_revision: Union[str, Sequence[str], None] = '9057408b1fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts') as batch_op:
        batch_op.create_foreign_key(
            'fk_alert_detection',
            'detections',
            ['detection_id'],
            ['id'],
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts') as batch_op:
        batch_op.drop_constraint('fk_alert_detection', type_='foreignkey')
    # ### end Alembic commands ###
