"""update_alert_schema

Revision ID: 801ef9ce7fd2
Revises: 58242672e49f
Create Date: 2025-11-10 06:05:37.625441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801ef9ce7fd2'
down_revision: Union[str, Sequence[str], None] = '58242672e49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('type', sa.String(), nullable=False, comment='Type of alert (e.g., poacher_suspected)'))
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=True, comment='Alert severity level'))
    op.add_column('alerts', sa.Column('source', sa.String(), nullable=True, comment='Source of the alert (e.g., camera_trap)'))
    op.add_column('alerts', sa.Column('notes', sa.String(), nullable=True, comment='Optional operator notes'))
    op.add_column('alerts', sa.Column('lat', sa.Float(), nullable=True, comment='Latitude of alert location'))
    op.add_column('alerts', sa.Column('lng', sa.Float(), nullable=True, comment='Longitude of alert location'))
    op.add_column('alerts', sa.Column('zone_label', sa.String(), nullable=True, comment='Label of the zone where alert was triggered'))
    op.add_column('alerts', sa.Column('created_by', sa.String(), nullable=True, comment='Operator who created the alert'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'created_by')
    op.drop_column('alerts', 'zone_label')
    op.drop_column('alerts', 'lng')
    op.drop_column('alerts', 'lat')
    op.drop_column('alerts', 'notes')
    op.drop_column('alerts', 'source')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'type')
    # ### end Alembic commands ###
