"""add alert model

Revision ID: 9057408b1fdc
Revises: 0c05d047390f
Create Date: 2025-11-07 10:22:27.881163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9057408b1fdc'
down_revision: Union[str, Sequence[str], None] = '0c05d047390f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the alert'),
    sa.Column('detection_id', sa.Integer(), nullable=False, comment='ID of the associated detection'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When the alert was created'),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'INACTIVE', name='alertstatus'), nullable=False, comment='Current status of the alert'),
    sa.Column('notification_sent', sa.Integer(), nullable=True, comment='Whether notification was sent (0=no, 1=yes)'),
    sa.Column('notification_timestamp', sa.DateTime(), nullable=True, comment='When notification was sent'),
    sa.Column('message', sa.String(), nullable=True, comment='Alert message or description'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
